# Q-Learning with OpenAI's Frozen Lake
## A neural network (scalable) approach to solving a simple RL environment.
### Adapted from https://medium.com/emergent-future/simple-reinforcement-learning-with-tensorflow-part-0-q-learning-with-tables-and-neural-networks-d195264329d0

In [4]:
import gym
import numpy as np
import random
import tensorflow as tf
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
environment = gym.make('FrozenLake-v0')

In [6]:
# Define my model as a 16 - 4 densely connected neural network
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(16,)),
    tf.keras.layers.Dense(4,activation='relu',kernel_initializer='RandomNormal')
])

In [7]:
s = np.random.random((1,16))
s = np.zeros((1,16))

print(s)
model.predict(s)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0.]], dtype=float32)

In [8]:
# Compile model with this loss function
model.compile(optimizer='adam', loss=custom_loss)

NameError: name 'custom_loss' is not defined

In [9]:
# Set the learning paramters
gamma = 0.99
epsilon = 0.1
num_episodes = 2000

rewards = []
episode_steps = []

In [10]:
# Train the network
for i in range(num_episodes):
    s = environment.reset()
    s = tf.one_hot(s, depth=environment.observation_space.n).numpy().reshape(1,16)
    done = False
    episode_rewards = []
    j = 0

    # Q Learning
    while j < 99: 
        j += 1
        # Select action by epsilon-greedy 
        if np.random.random() < epsilon:
            #a = np.random.choice(environment.action_space.n)
            a = environment.action_space.sample() # Use the buit in function
        else:
            a = np.argmax(model.predict(s)) # How do I choose action for max Q value?
        
        s_next, r, done, _ = environment.step(a)
        s_next = tf.one_hot(s_next, depth=environment.observation_space.n).numpy().reshape(1,16)
        print(s_next)
        # Create target for Bellman -> Q = predictedQ + learning_rate * (r + gamma * np.max(targetQ) - predictedQ) 
        
        
        ###############################################################
        with tf.GradientTape() as tape:
            targetQ = r + gamma * np.max(model.predict(s_next), axis=1)
            predictedQ = model.predict(s)
            tape.watch(model.trainable_variables)
            loss = tf.math.reduce_mean(tf.square(targetQ - predictedQ))
        variables = model.trainable_variables
        gradients = tape.gradient(loss, variables)

        model.optimizer.apply_gradients(zip(gradients, variables))
        ###############################################################

        episode_rewards += r
        s = s_next

        if done == True: # End the episode if done
            epsilon = 1./((i/50) + 10)
            break

    rewards.append(episode_rewards)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


LookupError: No gradient defined for operation 'IteratorGetNext' (op type: IteratorGetNext)

In [141]:
print ("Percent of succesful episodes: " + str(sum(rewards)/num_episodes) + "%")

Percent of succesful episodes: 0.0%


In [ ]:
plt.plot(rewards)
plt.plot(episode_steps)

In [ ]:

        with tf.GradientTape() as tape:
            tape.watch(model.trainable_variables)
            loss = tf.math.reduce_mean(tf.square(targetQ - predictedQ))
        variables = model.trainable_variables
        gradients = tape.gradient(loss, variables)

        model.optimizer.apply_gradients(zip(gradients, variables))